/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author FellerDénes(Szf_N_20
 */
public class GUINezetLampak extends javax.swing.JFrame {

    /**
     * Creates new form GUINezetLampak
     */
    public GUINezetLampak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlAdatok = new javax.swing.JPanel();
        jlblLekapcsoltLampakSzama = new javax.swing.JLabel();
        jlblJatekosnev = new javax.swing.JLabel();
        jtxtFldJatekosNev = new javax.swing.JTextField();
        jspnrLekapcsoltLampakSzama = new javax.swing.JSpinner();
        jlblJatekAllas = new javax.swing.JLabel();
        jPnlLampaTarolo = new javax.swing.JPanel();
        jbtnLampa0 = new javax.swing.JButton();
        jbtnLampa1 = new javax.swing.JButton();
        jbtnLampa2 = new javax.swing.JButton();
        jbtnLampa3 = new javax.swing.JButton();
        jbtnLampa4 = new javax.swing.JButton();
        jbtnLampa5 = new javax.swing.JButton();
        jbtnLampa6 = new javax.swing.JButton();
        jbtnLampa7 = new javax.swing.JButton();
        jbtnLampa8 = new javax.swing.JButton();
        jbtnUjra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmItemLeiras = new javax.swing.JMenuItem();
        jmItemMentes = new javax.swing.JMenuItem();
        jmItemBetoltes = new javax.swing.JMenuItem();
        jmItemKilepes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LightOn Játék");

        jPnlAdatok.setBorder(javax.swing.BorderFactory.createTitledBorder("Játékadatok"));

        jlblLekapcsoltLampakSzama.setText("Lekapcsolt lámpák száma:");

        jlblJatekosnev.setText("Játékosnév:");

        jspnrLekapcsoltLampakSzama.setEnabled(false);

        jlblJatekAllas.setForeground(new java.awt.Color(51, 51, 255));
        jlblJatekAllas.setText("NYERTÉL, XY! Lekapcsoltad az összes lámpát!");

        javax.swing.GroupLayout jPnlAdatokLayout = new javax.swing.GroupLayout(jPnlAdatok);
        jPnlAdatok.setLayout(jPnlAdatokLayout);
        jPnlAdatokLayout.setHorizontalGroup(
            jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdatokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblJatekAllas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPnlAdatokLayout.createSequentialGroup()
                        .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblJatekosnev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblLekapcsoltLampakSzama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFldJatekosNev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jspnrLekapcsoltLampakSzama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPnlAdatokLayout.setVerticalGroup(
            jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdatokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblLekapcsoltLampakSzama)
                    .addComponent(jspnrLekapcsoltLampakSzama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblJatekosnev)
                    .addComponent(jtxtFldJatekosNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblJatekAllas)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPnlLampaTarolo.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        jbtnLampa0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_sarga.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa0);

        jbtnLampa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_sarga.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa1);

        jbtnLampa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa2);

        jbtnLampa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa3);

        jbtnLampa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa4);

        jbtnLampa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa5);

        jbtnLampa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa6);

        jbtnLampa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa7);

        jbtnLampa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPnlLampaTarolo.add(jbtnLampa8);

        jbtnUjra.setText("Újraindít");

        jMenu1.setText("Műveletek");

        jmItemLeiras.setText("Leírás");
        jMenu1.add(jmItemLeiras);

        jmItemMentes.setText("Mentés");
        jMenu1.add(jmItemMentes);

        jmItemBetoltes.setText("Betöltés");
        jMenu1.add(jmItemBetoltes);

        jmItemKilepes.setText("Kilépés");
        jMenu1.add(jmItemKilepes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlLampaTarolo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnUjra, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnlLampaTarolo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnUjra)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    

    public JButton getJbtnLampa0() {
        return jbtnLampa0;
    }

    public JButton getJbtnLampa1() {
        return jbtnLampa1;
    }
    
    public JButton getJbtnLampa2() {
        return jbtnLampa2;
    }    

    public JButton getJbtnLampa3() {
        return jbtnLampa3;
    }

    public JButton getJbtnLampa4() {
        return jbtnLampa4;
    }

    public JButton getJbtnLampa5() {
        return jbtnLampa5;
    }

    public JButton getJbtnLampa6() {
        return jbtnLampa6;
    }

    public JButton getJbtnLampa7() {
        return jbtnLampa7;
    }

    public JButton getJbtnLampa8() {
        return jbtnLampa8;
    }
    
    public String getJtxtFldJatekosNev() {
        return jtxtFldJatekosNev.getText();
    }

    public void setJlblJatekAllas(String text) {
        this.jlblJatekAllas.setText(text);
    }

    public JButton getJbtnUjra() {
        return jbtnUjra;
    }

    public JMenuItem getJmItemKilepes() {
        return jmItemKilepes;
    }
    
    public JMenuItem getJmItemLeiras() {
        return jmItemLeiras;
    }

    public JMenuItem getJmItemBetoltes() {
        return jmItemBetoltes;
    }

    public JMenuItem getJmItemMentes() {
        return jmItemMentes;
    }

    
    
    public void setJspnrLekapcsoltLampakSzama(int szam) 
    {
        this.jspnrLekapcsoltLampakSzama.setValue(szam);
    }    

    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPnlAdatok;
    private javax.swing.JPanel jPnlLampaTarolo;
    private javax.swing.JButton jbtnLampa0;
    private javax.swing.JButton jbtnLampa1;
    private javax.swing.JButton jbtnLampa2;
    private javax.swing.JButton jbtnLampa3;
    private javax.swing.JButton jbtnLampa4;
    private javax.swing.JButton jbtnLampa5;
    private javax.swing.JButton jbtnLampa6;
    private javax.swing.JButton jbtnLampa7;
    private javax.swing.JButton jbtnLampa8;
    private javax.swing.JButton jbtnUjra;
    private javax.swing.JLabel jlblJatekAllas;
    private javax.swing.JLabel jlblJatekosnev;
    private javax.swing.JLabel jlblLekapcsoltLampakSzama;
    private javax.swing.JMenuItem jmItemBetoltes;
    private javax.swing.JMenuItem jmItemKilepes;
    private javax.swing.JMenuItem jmItemLeiras;
    private javax.swing.JMenuItem jmItemMentes;
    private javax.swing.JSpinner jspnrLekapcsoltLampakSzama;
    private javax.swing.JTextField jtxtFldJatekosNev;
    // End of variables declaration//GEN-END:variables
}
