/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import javax.swing.JButton;

/**
 *
 * @author FellerDénes(Szf_N_20
 */
public class GUINezetLampak extends javax.swing.JFrame {

    /**
     * Creates new form GUINezetLampak
     */
    public GUINezetLampak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlAdatok = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnLampa0 = new javax.swing.JButton();
        jbtnLampa1 = new javax.swing.JButton();
        jbtnLampa2 = new javax.swing.JButton();
        jbtnLampa3 = new javax.swing.JButton();
        jbtnLampa4 = new javax.swing.JButton();
        jbtnLampa5 = new javax.swing.JButton();
        jbtnLampa6 = new javax.swing.JButton();
        jbtnLampa7 = new javax.swing.JButton();
        jbtnLampa8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlAdatok.setBorder(javax.swing.BorderFactory.createTitledBorder("Játékadatok"));

        jLabel1.setText("Lekapcsolt lámpák száma:");

        jLabel2.setText("Lekapcsolt lámpák száma:");

        javax.swing.GroupLayout jPnlAdatokLayout = new javax.swing.GroupLayout(jPnlAdatok);
        jPnlAdatok.setLayout(jPnlAdatokLayout);
        jPnlAdatokLayout.setHorizontalGroup(
            jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdatokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPnlAdatokLayout.setVerticalGroup(
            jPnlAdatokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAdatokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jbtnLampa0.setBackground(new java.awt.Color(0, 204, 0));
        jbtnLampa0.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jbtnLampa0);

        jbtnLampa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_sarga.png"))); // NOI18N
        jPanel1.add(jbtnLampa1);

        jbtnLampa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa2);

        jbtnLampa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa3);

        jbtnLampa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa4);

        jbtnLampa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa5);

        jbtnLampa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa6);

        jbtnLampa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa7);

        jbtnLampa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nezet/lampa_zold.png"))); // NOI18N
        jPanel1.add(jbtnLampa8);

        jButton1.setText("Újraindít");

        jMenu1.setText("Műveletek");

        jMenuItem1.setText("Kilépés");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlAdatok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINezetLampak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINezetLampak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINezetLampak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINezetLampak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINezetLampak().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlAdatok;
    private javax.swing.JButton jbtnLampa0;
    private javax.swing.JButton jbtnLampa1;
    private javax.swing.JButton jbtnLampa2;
    private javax.swing.JButton jbtnLampa3;
    private javax.swing.JButton jbtnLampa4;
    private javax.swing.JButton jbtnLampa5;
    private javax.swing.JButton jbtnLampa6;
    private javax.swing.JButton jbtnLampa7;
    private javax.swing.JButton jbtnLampa8;
    // End of variables declaration//GEN-END:variables
}
